version: '3.8'

services:
  bot:
    image: servereye-bot:latest
    container_name: ServerEyeBot-TelegramBot
    restart: unless-stopped
    network_mode: host
    environment:
      - TELEGRAM_TOKEN=8370032634:AAFhXrh7tfITzgM9dPMMdTK5Z8utiv1p82g
      - DATABASE_URL=postgres://postgres:postgres123@127.0.0.1:5434/servereye?sslmode=disable
      - KEYS_DATABASE_URL=postgres://postgres:test123456@127.0.0.1:5432/PgRegisteredKeys?sslmode=disable
      - BACKEND_URL=https://api.servereye.dev:8443
      - API_KEY=sPnMkMxyxIcjq1kJD7FOtEjUrHxvSmEU
      - LOG_LEVEL=info
      - KAFKA_ENABLED=false
    ports:
      - '8091:8080'
    depends_on:
      - postgres
    volumes:
      - /etc/servereye:/etc/servereye:ro
      - ./logs:/app/logs

  postgres:
    image: postgres:15-alpine
    container_name: ServerEyeBot-Postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=servereye
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - servereye-network

volumes:
  postgres_data:

networks:
  servereye-network:
    external: true
